import { IAction as IAuthorizeAction, IAttributes as IAuthorizeActionAttributes } from '../action/authorize';
import { IAnonymousLocation, IAttributes as IMoneyTransferActionAttributes, IPaymentCard } from '../action/transfer/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../organization/project';
import OrganizationType from '../organizationType';
import { IPerson } from '../person';
import * as TransactionFactory from '../transaction';
import TransactionType from '../transactionType';

export type IAgent = IPerson;

export type IRecipient = IPerson | TransactionFactory.ISeller;

export import ISeller = TransactionFactory.ISeller;

export interface IStartParamsWithoutDetail {
    project: IProject;
    /**
     * 取引期限
     */
    expires: Date;
    /**
     * 転送人
     */
    agent: IAgent;
    /**
     * 受取人
     */
    recipient: IRecipient;
    seller: {
        typeOf: OrganizationType;
        id: string;
    };
    /**
     * 転送内容
     */
    object: IObject;
}

/**
 * 取引開始パラメーターインターフェース
 */
export interface IStartParams extends TransactionFactory.IStartParams<TransactionType.MoneyTransfer, IAgent, IRecipient, IObject> {
    /**
     * 転送先
     */
    recipient: IRecipient;
    /**
     * 販売者
     */
    seller: ISeller;
}

export type IResult = any;

/**
 * エラーインターフェース
 */
export type IError = any;

/**
 * トークン化された口座インターフェース
 */
export type ITokenizedAccount = string;

export type IFromLocation = IPaymentCard | ITokenizedAccount;
export type IToLocation = IPaymentCard | IAnonymousLocation;

/**
 * 取引対象物インターフェース
 */
export interface IObject {
    /**
     * 金額
     */
    amount: number;
    /**
     * 転送元
     */
    fromLocation: IFromLocation;
    /**
     * 転送先
     */
    toLocation: IToLocation;
    /**
     * 取引説明
     */
    description?: string;
    /**
     * 承認アクションリスト
     */
    authorizeActions: IAuthorizeAction<IAuthorizeActionAttributes<any, any>>[];
}

export interface IPotentialActions {
    /**
     * 通貨転送アクション
     */
    moneyTransfer: IMoneyTransferActionAttributes[];
}

export type ITransaction = IExtendId<IAttributes>;

/**
 * 転送取引インターフェース
 */
export interface IAttributes extends TransactionFactory.IAttributes<IStartParams, IResult, IError, IPotentialActions> {
}

export interface ISearchConditions extends TransactionFactory.ISearchConditions<TransactionType.MoneyTransfer> {
    seller?: {
        typeOf?: OrganizationType;
        ids?: string[];
    };
    object?: {
    };
    potentialActions?: {
    };
    result?: {
    };
}
