import { IExtendId } from '../autoGenerated';
import { IProject } from '../organization/project';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    project: IProject;
    /**
     * イベントID
     */
    id: string;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.AggregateEventReservations;
    data: IData;
}

/**
 * イベント予約集計タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
