import { IAttributes as ICancelActionAttributes } from '../action/organize/cancel';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = ICancelActionAttributes<any, any>;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelReservation;
    data: IData;
}

/**
 * 予約取消タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
