import { IPurpose } from '../action/authorize/offer/seatReservation';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    project: IProject;
    purpose: IPurpose;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelSeatReservation;
    data: IData;
}

/**
 * 座席予約承認取消タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
