import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    project?: IProject;
    transactionId: string;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelPointAward;
    data: IData;
}

/**
 * ポイントインセンティブ承認アクション取消タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
