import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.interact.confirm.moneyTransfer.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmMoneyTransfer;
    data: IData;
}

/**
 * 通貨転送タスクファクトリー
 */
export type ITask = IExtendId<IAttributes>;
