import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export import IObject4COA = chevre.action.transfer.returnAction.reservation.IObject4COA;
export import IObject4Chevre = chevre.action.transfer.returnAction.reservation.IObject4Chevre;
export import IObject = chevre.action.transfer.returnAction.reservation.IObject;

export type IPotentialActions = chevre.assetTransaction.cancelReservation.IPotentialActionsParams;

export type IData = chevre.action.transfer.returnAction.reservation.IAttributes<IObject<chevre.service.webAPI.Identifier>, any> & {
    potentialActions?: IPotentialActions;
};

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmCancelReserve;
    data: IData;
}

/**
 * 予約取消タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
