import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.transfer.returnAction.paymentMethod.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmRefund;
    data: IData;
}
/**
 * 返金タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
