import { IAttributes as IRegisterServiceActionAttributes } from '../action/interact/confirm/registerService';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRegisterServiceActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmRegisterService;
    data: IData;
}
/**
 * サービス登録タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
