import { IAttributes as IConfirmReservationActionAttributes } from '../action/interact/confirm/reservation';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = IConfirmReservationActionAttributes<chevre.service.webAPI.Identifier>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmReservation;
    data: IData;
}
/**
 * 予約確定タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
