import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.interact.confirm.pay.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmPay;
    data: IData;
}
/**
 * 決済タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
