import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.interact.confirm.registerService.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmRegisterService;
    data: IData;
}
/**
 * サービス登録タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
