import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.update.deleteAction.member.IAttributes;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.DeleteMember;
    data: IData;
}

/**
 * 会員削除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
