import { IAttributes as IDeleteMemberActionAttributes } from '../action/update/delete/member';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IDeleteMemberActionAttributes;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.DeleteMember;
    data: IData;
}

/**
 * 会員削除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
