import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.transfer.give.pointAward.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.GivePointAward;
    data: IData;
}
/**
 * ポイントインセンティブ付与タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
