import { IExtendId } from '../autoGenerated';
import { IOfferedThrough } from '../event/screeningEvent';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    project: IProject;
    /**
     * 劇場枝番号
     */
    locationBranchCode: string;
    /**
     * 仕入れ先サービス
     */
    offeredThrough?: IOfferedThrough;
    /**
     * 仕入れ期間from
     */
    importFrom: Date;
    /**
     * 仕入れ期間through
     */
    importThrough: Date;
    xmlEndPoint?: { baseUrl: string; theaterCodeName: string };
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ImportScreeningEvents;
    data: IData;
}
/**
 * 上映イベント在庫仕入れタスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
