import AccountType from '../accountType';
import { IAttributes as IMoneyTransferActionAttributes } from '../action/transfer/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IMoneyTransferActionAttributes<AccountType>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.MoneyTransfer;
    data: IData;
}

/**
 * 通貨転送タスクファクトリー
 */
export type ITask = IExtendId<IAttributes>;
