import { IExtendId } from '../autoGenerated';
import { IProgramMembership } from '../programMembership';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IAgent = chevre.action.IParticipant;
export type IAcceptedOffer = chevre.order.IAcceptedOffer<IProgramMembership>;
export type IPotentialActions = chevre.transaction.placeOrder.IPotentialActionsParams;

export interface IData {
    agent: IAgent;
    /**
     * 注文対象
     */
    object: IAcceptedOffer;
    /**
     * 注文取引確定後アクション
     */
    potentialActions?: IPotentialActions;
    project: chevre.project.IProject;
    typeOf: chevre.actionType.OrderAction;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OrderProgramMembership;
    data: IData;
}

/**
 * メンバーシップ注文タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
