import { IAttributes as IPayActionAttributes } from '../action/trade/pay';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IPayActionAttributes<PaymentMethodType.PrepaidCard>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PayPrepaidCard;
    data: IData;
}
/**
 * プリペイドカード決済タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
