import { IAttributes as IPayActionAttributes } from '../action/trade/pay';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IPayActionAttributes<any>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PayPaymentCard;
    data: IData;
}
/**
 * ペイメントカード決済タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
