import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';
import { ITransaction } from '../transaction/placeOrder';

export type IData = ITransaction;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PlaceOrder;
    data: IData;
}
/**
 * 注文タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
