import { IAttributes as IOrderActionAttributes } from '../action/trade/order';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IOrderActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PlaceOrder;
    data: IData;
}
/**
 * 注文タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
