import { IAttributes as IRefundActionAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRefundActionAttributes<PaymentMethodType.Point>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.RefundPoint;
    data: IData;
}
/**
 * ポイント返金タスクインタエーフェース
 */
export type ITask = IExtendId<IAttributes>;
