import { IAttributes as IRefundActionAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRefundActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.Refund;
    data: IData;
}
/**
 * 返金タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
