import { IAttributes as IRefundActionAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRefundActionAttributes<PaymentMethodType.MGTicket | PaymentMethodType.MovieTicket>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.RefundMovieTicket;
    data: IData;
}
/**
 * ムビチケ着券取消タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
