import { IAttributes as IRefundActionAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRefundActionAttributes<PaymentMethodType.PrepaidCard>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.RefundPrepaidCard;
    data: IData;
}
/**
 * プリペイドカード返金タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
