import { IAttributes as IRefundActionAttributes } from '../action/trade/refund';
import { IExtendId } from '../autoGenerated';
import PaymentMethodType from '../paymentMethodType';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IRefundActionAttributes<PaymentMethodType.Account>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.RefundAccount;
    data: IData;
}
/**
 * 口座返金タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
