import { IAttributes as IReturnPointAwardActionAttributes } from '../action/transfer/return/pointAward';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = IReturnPointAwardActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnPointAward;
    data: IData;
}
/**
 * ポイントインセンティブ返却タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
