import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.transfer.returnAction.pointAward.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnPointAward;
    data: IData;
}
/**
 * ポイントインセンティブ返却タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
