import { IAttributes as ISendOrderActionAttributes } from '../action/transfer/send/order';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = ISendOrderActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SendOrder;
    data: IData;
}
/**
 * 注文配送タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
