import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export interface IData {
    /**
     * Eメール送信アクション属性
     */
    actionAttributes: chevre.action.transfer.send.message.email.IAttributes;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SendEmailMessage;
    data: IData;
}
/**
 * Eメール送信タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
