import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.interact.inform.IAttributes<any, any>;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.TriggerWebhook;
    data: IData;
}

/**
 * ウェブフックタスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
