import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export type IData = chevre.action.interact.unRegister.programMembership.IAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.UnRegisterProgramMembership;
    data: IData;
}
/**
 * メンバーシップ登録解除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
