import { IExtendId } from '../autoGenerated';
import { IOfferedThrough } from '../event/screeningEvent';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    /**
     * 劇場枝番号
     */
    locationBranchCode: string;
    /**
     * 仕入れ先サービス
     */
    offeredThrough?: IOfferedThrough;
    /**
     * 仕入れ期間from
     */
    importFrom: Date;
    /**
     * 仕入れ期間through
     */
    importThrough: Date;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.UpdateEventAttendeeCapacity;
    data: IData;
}

/**
 * イベント席数更新タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
