import { IPurpose } from '../action/authorize/offer/seatReservation';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    agent?: { id: string };
    /**
     * 承認アクションID指定であれば、指定アクションのみ中止
     */
    id?: string;
    project: IProject;
    purpose: IPurpose;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.VoidReserveTransaction;
    data: IData;
}

/**
 * 予約承認取消タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
