import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

import * as chevre from '../../chevre';

export interface IData {
    agent?: { id: string };
    /**
     * 承認アクションID指定であれば、指定アクションのみ中止
     */
    id?: string;
    project: chevre.project.IProject;
    purpose: chevre.action.authorize.offer.product.IPurpose;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.VoidRegisterServiceTransaction;
    data: IData;
}

/**
 * サービス登録中止タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
