import { seller } from '../chevre';

export import ILocation = seller.ILocation;
export import IParentOrganization = seller.IParentOrganization;
export import IAcceptedPaymentMethodType = seller.IAcceptedPaymentMethodType;
export import IGMOInfo = seller.IGMOInfo;
export import IMovieTicketInfo = seller.IMovieTicketInfo;
export import ICashPaymentAccepted = seller.ICashPaymentAccepted;
export import ICreditCardPaymentAccepted = seller.ICreditCardPaymentAccepted;
export import IEMoneyPaymentAccepted = seller.IEMoneyPaymentAccepted;
export import IAccountPaymentAccepted = seller.IAccountPaymentAccepted;
export import IMovieTicketPaymentAccepted = seller.IMovieTicketPaymentAccepted;
export import ICommonPaymentAccepted = seller.ICommonPaymentAccepted;
export import IPaymentAccepted = seller.IPaymentAccepted;
export import IMakesOffer = seller.IMakesOffer;
export import IAreaServed = seller.IAreaServed;
export import IHasMerchantReturnPolicy = seller.IHasMerchantReturnPolicy;
export import IAttributes = seller.IAttributes;
export import IOrganization = seller.IOrganization;
export import ISearchConditions = seller.ISearchConditions;
